"""Requirements-file generator for agents-plugin graphs.

Walks the graph, maps each node type to its pip requirements, and emits
a pinned `requirements.txt` string. Versions come from the currently
installed packages (via `importlib.metadata`); if a package isn't
installed, the requirement is emitted without a version pin.

Key invariant (DESIGN.md §G.3): a graph with ONLY LLM client + agent +
tool nodes (no EmbedderNode, no MemoryStoreNode) must NOT pull torch.
Torch only enters the requirements when sentence-transformers is required.
"""
from __future__ import annotations
from dataclasses import dataclass


# Map: node.type_name → list of pip package names
# Keep this table narrow: only the packages the exported script's code
# ACTUALLY imports at runtime. MCPToolNode pulls `mcp`; MemoryStoreNode
# pulls `qdrant-client`; EmbedderNode (non-hash) pulls both
# `sentence-transformers` and `torch`.
_NODE_REQUIREMENTS: dict[str, list[str]] = {
    "ag_ollama_client":         ["ollama"],
    "ag_openai_compat_client":  ["openai"],
    "ag_llama_cpp_client":      ["llama-cpp-python"],
    "ag_embedder":              ["sentence-transformers", "torch"],
    "ag_memory_store":          ["qdrant-client"],
    "ag_retriever":             ["qdrant-client"],
    "ag_mcp_tool":              ["mcp"],
    # ag_document_loader, ag_chat_message, ag_conversation,
    # ag_prompt_template, ag_agent, ag_tool, ag_python_function_tool
    # use only stdlib → no entries.
}

# For an EmbedderNode configured with model="hash-*" we skip sentence-transformers.
# Detected by inspecting the node's `model` input default when walking the graph.


@dataclass
class RequirementLine:
    package: str
    version: str = ""      # empty when not installed

    def format(self) -> str:
        return f"{self.package}=={self.version}" if self.version else self.package


def collect_requirements(graph) -> list[RequirementLine]:
    """Return the deduped, sorted list of RequirementLines a graph's export
    would need. Order is alphabetic by package name.
    """
    packages: set[str] = set()
    for node in graph.nodes.values():
        tn = getattr(node, "type_name", "")
        packages.update(_NODE_REQUIREMENTS.get(tn, []))
        # EmbedderNode with a hash-* model skips sentence-transformers+torch
        if tn == "ag_embedder":
            model = _node_input_default(node, "model", "")
            if isinstance(model, str) and model.startswith("hash"):
                packages.discard("sentence-transformers")
                packages.discard("torch")
    return [
        RequirementLine(package=pkg, version=_installed_version(pkg))
        for pkg in sorted(packages)
    ]


def render_requirements(graph) -> str:
    """Serialize a graph's requirements as a standalone file body.

    Empty line + header when no deps are needed (so `pip install -r` is a
    valid no-op rather than an error).
    """
    reqs = collect_requirements(graph)
    lines = [
        "# Generated by node-tool plugins/agents — requirements for the",
        "# exported graph. Versions pinned to what's installed locally; "
        "unpinned",
        "# entries mean the package wasn't installed at export time.",
    ]
    if not reqs:
        lines.append("")
        lines.append("# (no third-party requirements — stdlib only)")
    else:
        lines.append("")
        for r in reqs:
            lines.append(r.format())
    return "\n".join(lines) + "\n"


def _node_input_default(node, port_name: str, fallback):
    port = getattr(node, "inputs", {}).get(port_name)
    if port is None:
        return fallback
    return getattr(port, "default_value", fallback)


def _installed_version(package: str) -> str:
    """Return the pip-reported version of `package`, or empty string if
    not installed. Uses importlib.metadata (stdlib since 3.8).
    """
    try:
        from importlib.metadata import version, PackageNotFoundError
    except ImportError:
        return ""
    try:
        return version(package)
    except Exception:
        return ""
