"""GraphExporter — export a Graph to a runnable Python script."""
from __future__ import annotations
from core.graph import Graph
from core.node import BaseNode


_PREFIX_STRIP = ("pt_", "np_", "pd_", "sk_", "sp_", "viz_")


def _short(type_name: str) -> str:
    """Turn a type_name into a clean variable prefix."""
    s = type_name
    for p in _PREFIX_STRIP:
        if s.startswith(p):
            s = s[len(p):]
            break
    s = s.replace("__terminal__", "terminal")
    return s or type_name


class GraphExporter:
    """Export a Graph to a runnable Python script."""

    def export(self, graph: Graph) -> str:
        order = graph.topological_order()
        if not order:
            return "# Empty graph — nothing to export.\n"

        # Build connection lookup: (to_node_id, to_port) -> (from_node_id, from_port)
        conn_map: dict[tuple[str, str], tuple[str, str]] = {}
        for c in graph.connections:
            conn_map[(c.to_node_id, c.to_port)] = (c.from_node_id, c.from_port)

        # Map (node_id, port_name) -> variable name for each output port
        var_map: dict[tuple[str, str], str] = {}
        port_counters: dict[str, int] = {}

        def assign_out_vars(node: BaseNode) -> dict[str, str]:
            out_vars: dict[str, str] = {}
            prefix = _short(node.type_name)
            for port_name in node.outputs:
                if port_name == "__terminal__":
                    continue
                key = f"{prefix}_{port_name}"
                port_counters[key] = port_counters.get(key, 0)
                if len(node.outputs) <= 1:
                    vname = f"{prefix}_{port_counters[key]}"
                else:
                    vname = f"{prefix}_{port_name}_{port_counters[key]}"
                port_counters[key] += 1
                out_vars[port_name] = vname
                var_map[(node.id, port_name)] = vname
            return out_vars

        all_imports: list[str] = []
        all_blocks: list[str] = []

        for node_id in order:
            node = graph.nodes[node_id]

            # Build in_vars: port_name -> variable expression (or None)
            in_vars: dict[str, str | None] = {}
            for port_name in node.inputs:
                key = (node_id, port_name)
                if key in conn_map:
                    from_node_id, from_port = conn_map[key]
                    in_vars[port_name] = var_map.get((from_node_id, from_port))
                else:
                    in_vars[port_name] = None

            out_vars = assign_out_vars(node)

            try:
                imports, lines = node.export(in_vars, out_vars)
                all_imports.extend(imports)
                if lines:
                    all_blocks.append(f"# {node.label}")
                    all_blocks.extend(lines)
                    all_blocks.append("")
            except Exception as exc:
                all_blocks.append(f"# [{node.label}]: export error -- {exc}")

        # Deduplicate imports, keeping order
        seen: set[str] = set()
        deduped: list[str] = []
        for imp in all_imports:
            if imp not in seen:
                seen.add(imp)
                deduped.append(imp)

        # Group: stdlib then third-party
        stdlib = [i for i in deduped if i.startswith(("import math", "import random", "import json"))]
        third_party = [i for i in deduped if i not in stdlib]

        header = ["# Generated by Node Tool v5", ""]
        import_block = stdlib + ([""] if stdlib and third_party else []) + third_party

        sections = header + import_block + ([""] if import_block else []) + all_blocks
        return "\n".join(sections).rstrip() + "\n"
